### ISSUE TITLE
2024LCK的导入有问题，时间不对

### ISSUE THREAD

**Issue by lidapao197** [ChengLuffy/lpl.ics#10]
是时区的问题吗，我已经改成上海时区的了

**Comment by ChengLuffy** [comment]
lck 的数据源已经开始的比赛是实际开始比赛的时间，在比赛开始后时间会更新，如果提前或延后了几十分钟属于正常现象

如果有几个小时的误差请提供下所使用的日历软件

**Comment by lidapao197** [comment]
往后了8小时，我用window11自带日历软件导入的还有荣耀手机自带的日历软件也是这样

**Comment by ChengLuffy** [comment]
好的，我手头没有 Windows 和 Android 手机，等明天我试着修复下，谢谢反馈

**Comment by ChengLuffy** [comment]
我在 Google 日历中测试时间对了，你有时间可以验证一下

**Comment by lidapao197** [comment]
可以了谢谢，我还想问下，https://pandascore.co  网站的获取赛事比赛的请求参数是怎么样的，接口文档有点看不懂

**Comment by ChengLuffy** [comment]
没什么经验，`LANGUAGE` 选择 `Python` 或者自己熟悉的语言，然后在 `QUERY PARAMS` 调参数，根据请求结果进行调整

**Comment by lidapao197** [comment]
就是参数不知道怎么设置，比如获取24年lck春季赛赛程，这个用java怎么设置

**Comment by ChengLuffy** [comment]
https://github.com/TankNee/LOL_Game_Subscription/pull/9/files

参考这里，293是 LCK 比赛，世界赛和季中应该是297和300，这个我当初是先不加参数然后根据返回结果添加筛选的

**Comment by lidapao197** [comment]
好的，谢谢
