### ISSUE TITLE
建议发布Release

### ISSUE THREAD

**Issue by TankNee** [ChengLuffy/lpl.ics#2]
用cdn速度会快很多

**Comment by ChengLuffy** [comment]
有比分，写了个脚本每隔一段时间更新一下，release 要手动，感觉比较麻烦

**Comment by TankNee** [comment]
可以用github action自动发release，这样我们只要用同一条cdn链接就能拿到最新的数据。
----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："chenluffy ***@***.***&gt;;
发送时间：2021年3月14日(星期天) 晚上8:17
收件人："ChengLuffy/lpl.ics" ***@***.***&gt;;
抄送："TankNee ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [ChengLuffy/lpl.ics] 建议发布Release (#2)
-----------------------------------

 

 
有比分，写了个脚本每隔一段时间更新一下，release 要手动，感觉比较麻烦

**Comment by TankNee** [comment]
可以参考我这个仓库的实现
https://github.com/TankNee/BingPic/blob/master/.github/workflows/main.yml
定时也好，push时触发也好，都能实现。

**Comment by TankNee** [comment]
其实脚本也能直接用GitHub Actions，这样流程会更方便一些？考虑把脚本也一起开源吗。

**Comment by ChengLuffy** [comment]
有时间我试下

脚本就是 python 的 JSON 解析、数据库处理、日历文件生成，很基础，开源很羞耻

数据源：[掌上英雄联盟LPL比赛数据源](https://lpl.qq.com/web201612/data/LOL_MATCH2_MATCH_HOMEPAGE_BMATCH_LIST.js)

**Comment by TankNee** [comment]
> 有时间我试下
> 
> 脚本就是 python 的 JSON 解析、数据库处理、日历文件生成，很基础，开源很羞耻
> 
> 数据源：[掌上英雄联盟LPL比赛数据源](https://lpl.qq.com/web201612/data/LOL_MATCH2_MATCH_HOMEPAGE_BMATCH_LIST.js)

这是官方的数据源吗，这也太全了吧哈哈哈，有时间我也写个试试。

**Comment by TankNee** [comment]
@ChengLuffy 您好，请问赛事结果要在哪里找呢？我找了半天好像没找到现成的API，要自己爬取网页吗

**Comment by ChengLuffy** [comment]
`ScoreA` `ScoreB`

**Comment by TankNee** [comment]
> `ScoreA` `ScoreB`

哦哦，是我看走眼了😂

**Comment by TankNee** [comment]
@ChengLuffy 搞定了，感觉还不错https://github.com/TankNee/LOL_Game_Subscription
