### ISSUE TITLE
添加MSI赛程

### ISSUE THREAD

**Issue by PPP1G** [ChengLuffy/lpl.ics#4]

**Comment by ChengLuffy** [comment]
已经更新，详见 d510091b24c26b0bbcdba27a2342c0e194c9bb6b ，如果手机上没有更新显示可以重新导入试试，出现这种情况的原因不明

**Comment by Axiso** [comment]
加赛的赛程也有了，你好敬业啊哈哈哈
lpl粉丝狂喜
