### ISSUE TITLE
添加 LPL 夏季赛日程

### ISSUE THREAD

**Issue by PPP1G** [ChengLuffy/lpl.ics#5]
官方已更新[夏季赛赛程](https://lol.qq.com/news/detail.shtml?type=1&docid=17810539788831938940)，我又来催更了。
以及，官方更新赛程时是否可以实现自动化更新？

**Comment by ChengLuffy** [comment]
夏季赛赛程已更新

数据是定时抓取掌盟数据做的更新，为了避免触发反爬虫机制，比赛时间段半小时抓取一次，如果是我喜欢的战队的比赛赢的话，打完我会手动更新一次
