### ISSUE TITLE
可以求 LDL 和 LCK 的ics吗？

### ISSUE THREAD

**Issue by dustiarmor** [ChengLuffy/lpl.ics#6]
老师好，请问数据源是直接抓官网的记录吗？
可以做ldl和lck的日历吗，感恩

**Comment by ChengLuffy** [comment]
LDL 的有数据，但是 LDL 真的有人看吗？

LCK 暂时没有找到合适的数据源

**Comment by dustiarmor** [comment]
我在https://github.com/TankNee/LOL_Game_Subscription/tree/master/2023_ldl这里看到了，谢谢~

**Comment by ChengLuffy** [comment]
@dustiarmor LCK 的赛程日历已经更新
